spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cooking_log
    username: cooking_log
    password: cooking_log

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/cooking_log
    user: cooking_log
    password: cooking_log

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: NEVER
